name: Gradle Wrapper Validation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:

jobs:
  validation:
    name: Validate Gradle Wrapper
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v3
